export function repeatedCaption(description,sets,records,excludeId=''){
  const normalize=s=>String(s||'').normalize('NFKC').replace(/[\s。.!！?？]+/g,'').toLocaleLowerCase();
  const target=normalize(description);if(!target)return [];
  return [...sets.filter(s=>s.id!==excludeId).map(s=>({id:s.id,name:s.name||s.id,description:s.description,at:s.updatedAt})),...records.map(r=>({id:r.id,name:r.song||r.id,description:r.description,at:r.postedAt||r.preparedAt}))].filter(r=>normalize(r.description)===target).sort((a,b)=>String(b.at).localeCompare(String(a.at)));
}
export function historyRows(sets,records){return [...sets.map(s=>({id:s.id,name:s.name||s.id,category:s.category,music:s.music?.title||'',description:s.description,hashtags:s.hashtags,at:s.publishedAt||s.scheduledAt||s.updatedAt,status:s.status,url:s.publishedUrl||'',views:null,source:'セット'})),...records.map(r=>({id:r.id,name:r.id,category:r.category||'未記録',music:r.song,description:r.description,hashtags:r.hashtags,at:r.postedAt||r.preparedAt,status:r.postUrl?'投稿済み（本人記録）':'準備記録',url:r.postUrl,views:r.views,source:'投稿記録'}))].sort((a,b)=>String(b.at).localeCompare(String(a.at)));}
export function selectedIndex(select,length){const raw=String(select.value??'');if(!/^\d+$/.test(raw)||!Array.from(select.children).some(o=>String(o.value)===raw))return -1;const i=Number(raw);return i<length?i:-1;}
export function dateRange(rows,from='',to=''){if(from&&to&&from>to)throw Error('開始日は終了日以前にしてください');return rows.filter(s=>{if(!from&&!to)return true;if(!s.scheduledAt)return false;const day=new Date(Date.parse(s.scheduledAt)+9*3600000).toISOString().slice(0,10);return (!from||day>=from)&&(!to||day<=to);});}
export function storageWrite(storage,key,value,blocked=false){if(blocked)return {ok:false,message:'既存保存データを保護中です。元データを退避してから明示的に保存を再開してください'};try{storage.setItem(key,JSON.stringify(value));return {ok:true,message:'端末保存済み'};}catch{return {ok:false,message:'端末保存失敗。画面内の変更は未保存です。JSON出力で退避し、保存を再試行してください'};}}
