export const LIMITS={count:35,total:100*1024*1024,file:20*1024*1024,pixels:24000000,zip:50*1024*1024};
export const dimensions={'3:4':[900,1200],'4:3':[1200,900],'16:9':[1600,900]};
export function filename(index){if(!Number.isInteger(index)||index<0||index>=35)throw Error('写真番号が不正です');return `FieldRise_TikTok_${String(index+1).padStart(3,'0')}.jpg`;}
export function admit(existing,file){if(existing.length>=LIMITS.count)throw Error('最大35枚です');if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>LIMITS.file)throw Error('JPG・PNG・WebP、20 MiB以下の画像を選んでください');if(existing.reduce((a,b)=>a+(b.size||0),0)+file.size>LIMITS.total)throw Error('合計100 MiBを超えます');}
export function move(rows,index,delta){const target=index+delta;if(index<0||index>=rows.length||target<0||target>=rows.length)return [...rows];const a=[...rows];[a[index],a[target]]=[a[target],a[index]];return a;}
export function settings(v={}){const ratio=v.ratio||'3:4';if(!dimensions[ratio])throw Error('画像比率が不正です');const x=Number(v.x??50),y=Number(v.y??50);if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>100||y<0||y>100)throw Error('切り抜き位置が不正です');return {ratio,x,y};}
export function postSet(v){if(!v||typeof v!=='object'||!Array.isArray(v.photos)||v.photos.length>35)throw Error('投稿セット形式が不正です');const str=(x,n)=>{if(typeof x!=='string'||x.length>n)throw Error('セット文字列が不正です');if(/(?:-----BEGIN .*PRIVATE KEY|eyJ[A-Za-z0-9_-]{20,}\.|gh[pousr]_[A-Za-z0-9]{30,}|sk-[A-Za-z0-9]{24,})/.test(x))throw Error('秘密値と思われる入力は保存できません');return x;};const photos=v.photos.map(p=>{if(!p||!Number.isSafeInteger(p.size)||p.size<1||p.size>LIMITS.file)throw Error('写真情報が不正です');return {id:str(p.id,120),name:str(p.name,300),size:p.size,lastModified:Number(p.lastModified)||0,...settings(p)};});if(new Set(photos.map(p=>p.id)).size!==photos.length||photos.reduce((a,p)=>a+p.size,0)>LIMITS.total)throw Error('重複写真IDまたは容量超過です');if(!v.id||!Number.isFinite(Date.parse(v.createdAt))||!Number.isFinite(Date.parse(v.updatedAt)))throw Error('セットID/日時が不正です');return {...Object.fromEntries(['category','customCategory','captionLength','status','scheduledAt','publishedAt','publishedUrl','statusHistory'].map(k=>[k,v[k]])),id:str(v.id,120),name:str(v.name||'',120),createdAt:v.createdAt,updatedAt:v.updatedAt,photos,photoCount:photos.length,music:v.music||null,title:str(v.title||'',90),description:str(v.description||'',1500),hashtags:str(v.hashtags||'',300),override:str(v.override||'',500),distributionChecked:v.distributionChecked===true,finalSoundChecked:v.finalSoundChecked===true,ready:v.ready===true&&v.music?.match==='確認済み'&&v.distributionChecked===true&&v.finalSoundChecked===true&&photos.length>0&&Boolean(v.title?.trim()&&v.description?.trim())};}
const crcTable=Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
export function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function header(size){const a=new Uint8Array(size);return [a,new DataView(a.buffer)];}
export async function zip(entries){if(!entries.length||entries.length>35)throw Error('ZIPの写真枚数が不正です');let offset=0,total=0;const locals=[],central=[];const names=new Set();for(const e of entries){if(!/^FieldRise_TikTok_\d{3}\.jpg$/.test(e.name)||names.has(e.name))throw Error('ZIPファイル名が不正または重複です');names.add(e.name);const bytes=new Uint8Array(await e.blob.arrayBuffer());total+=bytes.length;if(total>LIMITS.zip)throw Error('ZIP出力が50 MiBを超えます。個別保存してください');const name=new TextEncoder().encode(e.name),crc=crc32(bytes),[l,lv]=header(30+name.length);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint32(14,crc,true);lv.setUint32(18,bytes.length,true);lv.setUint32(22,bytes.length,true);lv.setUint16(26,name.length,true);l.set(name,30);locals.push(l,bytes);const [c,cv]=header(46+name.length);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=l.length+bytes.length;}
const [end,ev]=header(22);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,central.reduce((a,c)=>a+c.length,0),true);ev.setUint32(16,offset,true);return new Blob([...locals,...central,end],{type:'application/zip'});}
export function headerDimensions(b,type){let w=0,h=0;const v=new DataView(b.buffer,b.byteOffset,b.byteLength);if(type==='image/png'&&b.length>=24){w=v.getUint32(16);h=v.getUint32(20);}else if(type==='image/jpeg'){let i=2;while(i+9<b.length){if(b[i]!==255){i++;continue;}const marker=b[i+1];if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)){h=v.getUint16(i+5);w=v.getUint16(i+7);break;}if(marker===0xd8||marker===0xd9){i+=2;continue;}const length=v.getUint16(i+2);if(length<2)break;i+=2+length;}}else if(type==='image/webp'&&b.length>=30){const kind=String.fromCharCode(...b.slice(12,16));if(kind==='VP8X'){w=1+b[24]+(b[25]<<8)+(b[26]<<16);h=1+b[27]+(b[28]<<8)+(b[29]<<16);}else if(kind==='VP8 '){w=v.getUint16(26,true)&0x3fff;h=v.getUint16(28,true)&0x3fff;}else if(kind==='VP8L'&&b[20]===47){const bits=v.getUint32(21,true);w=(bits&0x3fff)+1;h=((bits>>>14)&0x3fff)+1;}}if(!w||!h)throw Error('安全に画像寸法を確認できません。通常のJPG/PNG/WebPへ再保存してください');if(w*h>LIMITS.pixels||w>10000||h>10000)throw Error('24百万画素・各辺10000以下にしてください');return {w,h};}
