import {workflow} from './workflow.mjs';
import {postSet} from './batch.mjs';
import {safeUrl,seed} from './core.mjs';
export const VERSION=4;
const states=['未確認','確認済み','不一致'];
function text(v,max=500){if(v==null)return '';if(typeof v!=='string'||v.length>max)throw Error('文字列形式または長さが不正です');if(/(?:-----BEGIN .*PRIVATE KEY|eyJ[A-Za-z0-9_-]{20,}\.|gh[pousr]_[A-Za-z0-9]{30,}|sk-[A-Za-z0-9]{24,})/.test(v))throw Error('秘密値と思われる入力は保存できません');return v.trim();}
function id(v){const s=text(v,120);if(s&&!/^[A-Za-z0-9_-]+$/.test(s))throw Error('IDは英数字・ハイフン・下線のみです');return s;}
function number(v){if(v===''||v==null)return null;if(!['string','number'].includes(typeof v))throw Error('数値形式が不正です');const n=Number(v);if(!Number.isSafeInteger(n)||n<0)throw Error('数値は0以上の整数にしてください');return n;}
function date(v){const s=text(v,100);if(s&&!Number.isFinite(Date.parse(s)))throw Error('日時形式が不正です');return s;}
export function music(v){if(!v||typeof v!=='object'||Array.isArray(v))throw Error('楽曲形式が不正です');const title=text(v.title,120),artist=text(v.artist,120);if(!title||!artist)throw Error('楽曲名・アーティストは必須です');const duration=text(v.duration,20);if(!/^\d{1,3}:[0-5]\d$/.test(duration))throw Error('時間は分:秒形式です');const isrc=text(v.isrc,12).toUpperCase();if(isrc&&!/^[A-Z]{2}[A-Z0-9]{3}\d{7}$/.test(isrc))throw Error('ISRC形式が不正です');const match=v.match||'未確認';if(!states.includes(match))throw Error('一致状態が不正です');const soundUrl=safeUrl(text(v.soundUrl,1000));if(soundUrl&&!['www.tiktok.com','tiktok.com'].includes(new URL(soundUrl).hostname))throw Error('公式音源URLはTikTokのURLにしてください');const reviewer=text(v.reviewer,120),verifiedAt=date(v.verifiedAt),method=text(v.method,120),evidence=text(v.evidence,1000);const soundOnId=id(v.soundOnId),tiktokId=id(v.tiktokId);if(match==='確認済み'&&(!reviewer||!verifiedAt||!method||!evidence||!soundUrl||!isrc&&!soundOnId))throw Error('確認済みには配信識別情報・公式URL・確認者・日時・方法・対応根拠が必要です');return {id:id(v.id)||crypto.randomUUID(),title,artist,duration,seconds:duration.split(':').reduce((a,b)=>a*60+Number(b),0),isrc,soundOnId,tiktokId,soundUrl,distribution:text(v.distribution,200),search:text(v.search,200),match,reviewer,verifiedAt,method,evidence};}
export function record(v){if(!v||typeof v!=='object'||Array.isArray(v))throw Error('投稿記録形式が不正です');const r={id:id(v.id)||crypto.randomUUID(),preparedAt:date(v.preparedAt),postedAt:date(v.postedAt),platform:'TikTok',format:'写真',photoSetId:id(v.photoSetId),photoCount:number(v.photoCount),song:text(v.song,120),artist:text(v.artist,120),image:text(v.image,300),title:text(v.title,90),description:text(v.description,1500),hashtags:text(v.hashtags,300),postUrl:safeUrl(text(v.postUrl,1000)),views:number(v.views),likes:number(v.likes),comments:number(v.comments),shares:number(v.shares),uses:number(v.uses),revenue:text(v.revenue,500),revenueStatus:v.revenueStatus||'未確認',revenueAmount:v.revenueAmount==null||v.revenueAmount===''?null:Number(v.revenueAmount),match:v.match||v.music?.match||'未確認',override:text(v.override,500),finalSoundChecked:v.finalSoundChecked===true,distributionChecked:v.distributionChecked===true,music:v.music?music(v.music):null,notes:text(v.notes,1000)};if(r.match==='確認済み'&&r.music?.match!=='確認済み')throw Error('確認済み記録には確認済み音源根拠が必要です');if(!states.includes(r.match)||!['未確認','集計待ち','確認済み（集計値・投稿因果未確認）'].includes(r.revenueStatus))throw Error('確認状態が不正です');if(r.revenueAmount!==null&&(!Number.isFinite(r.revenueAmount)||r.revenueAmount<0))throw Error('収益値が不正です');if(r.revenueStatus!=='確認済み（集計値・投稿因果未確認）'&&r.revenueAmount!==null)throw Error('未確認の収益を数値登録できません');if(Boolean(r.postUrl)!==Boolean(r.postedAt))throw Error('投稿URLと日時は両方入力してください');return {...r,state:r.postUrl?'published_owner_reported':'prepared',revenueVerified:false};}
export function migrate(input){if(!input||typeof input!=='object'||Array.isArray(input)||![undefined,1,2,3,4].includes(input.schemaVersion)||!Array.isArray(input.songs)||!Array.isArray(input.records)||input.songs.length>1000||input.records.length>10000)throw Error('バックアップ形式・バージョン・件数が不正です');const songs=input.songs.map(music),records=input.records.map(record);for(const rows of [songs,records])if(new Set(rows.map(x=>x.id)).size!==rows.length)throw Error('重複IDがあります');const sets=(input.sets||[]);if(!Array.isArray(sets)||sets.length>1000)throw Error('セット形式が不正です');const checked=sets.map(v=>postSet({...v,music:v.music?music(v.music):null}));if(new Set(checked.map(s=>s.id)).size!==checked.length)throw Error('重複セットIDです');return {schemaVersion:VERSION,songs:songs.length?songs:[music(seed)],records,sets:checked.map(v=>({...v,...workflow(v)}))};}
export function merge(current,incoming){const a=migrate(current),b=migrate(incoming);for(const key of ['songs','records','sets']){const ids=new Set(a[key].map(x=>x.id));if(b[key].some(x=>ids.has(x.id)))throw Error('既存IDと重複します。上書きしません');a[key].push(...b[key]);}return migrate(a);}
export function preflight({image,title,description,selected,distribution,match,final,override}){const warnings=[];if(!image)warnings.push('写真未準備');if(!title?.trim()||!description?.trim())warnings.push('投稿文未準備');if(!selected)warnings.push('楽曲未選択');if(!distribution)warnings.push('SoundOn配信情報未確認');if(match!=='確認済み')warnings.push('公式音源'+(match||'未確認'));if(!final)warnings.push('Studio最終音源未確認');const basics=Boolean(image&&title?.trim()&&description?.trim()&&selected);const ready=basics&&distribution&&match==='確認済み'&&final;return {warnings,ready,mayProceed:ready||basics&&match!=='不一致'&&Boolean(override?.trim()),label:ready?'投稿準備確認済み':match==='不一致'?'不一致：準備完了にできません':override?.trim()&&basics?'未確認あり：社長判断で準備継続':'確認が必要です'};}
export function csv2(rows){const keys=['id','preparedAt','postedAt','platform','format','photoSetId','photoCount','song','artist','match','image','title','description','hashtags','postUrl','views','likes','comments','shares','uses','revenueStatus','revenueAmount','override','notes'];const cell=v=>{let s=String(v??'');if(/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');}
