import {seed,crop,generate,safeUrl,csv} from './core.mjs';
const $=id=>document.getElementById(id), key='fieldrise-photo-v1';let songs=[seed],records=[],image=null,imageName='',loadSeq=0;
function notice(s){$('status').textContent=s;}try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.songs)&&Array.isArray(saved.records)){songs=saved.songs.length?saved.songs:[seed];records=saved.records;}}catch{notice('保存データを読み込めませんでした。新規状態で開始します。');}
function persist(){try{localStorage.setItem(key,JSON.stringify({songs,records}));return true;}catch{notice('端末保存に失敗しました。JSON出力でバックアップしてください。');return false;}}
function song(){return songs[Number($('songs').value)]||seed;}function list(){const sel=$('songs');sel.replaceChildren();songs.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.title+' / '+s.artist;sel.append(o);});info();}function info(){$('songInfo').textContent=song().duration+' · '+song().distribution+' · '+song().search;$('history').textContent='保存記録：'+records.length+'件（準備と公開確認を区別）';}list();$('songs').onchange=info;
$('songForm').onsubmit=e=>{e.preventDefault();try{const isrc=$('isrc').value.trim().toUpperCase();if(isrc&&!/^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$/.test(isrc))throw Error('ISRCは12文字の標準形式で入力してください');songs.push({title:$('songTitle').value.trim(),artist:$('artist').value.trim(),duration:$('duration').value,isrc,distribution:$('distribution').value,search:$('search').value,soundUrl:safeUrl($('soundUrl').value)});list();$('songs').value=songs.length-1;info();persist();notice('楽曲を登録しました。配信識別と収益の照合は別途必要です。');}catch(e){notice(e.message);}};
async function load(file){const seq=++loadSeq;image=null;$('download').disabled=true;$('preview').getContext('2d').clearRect(0,0,$('preview').width,$('preview').height);try{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>20*1024*1024)throw Error('JPG・PNG・WebP、20 MiB以下の画像を選んでください');const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const valid=file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:file.type==='image/png'?bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!valid)throw Error('画像形式とファイル内容が一致しません');const url=URL.createObjectURL(file);const img=new Image();try{img.src=url;await img.decode();}finally{URL.revokeObjectURL(url);}if(seq!==loadSeq)return;if(img.naturalWidth*img.naturalHeight>24000000||img.naturalWidth>10000||img.naturalHeight>10000)throw Error('画像が大きすぎます。24百万画素・各辺10000以下にしてください');image=img;imageName=file.name;$('meta').textContent=file.name+' / '+img.naturalWidth+' × '+img.naturalHeight+' / '+(img.naturalWidth/img.naturalHeight).toFixed(3);render();notice('画像を読み込みました。切り抜き位置を確認してください。');}catch(e){if(seq===loadSeq)notice(e.message);}}
$('image').onchange=e=>load(e.target.files[0]);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length!==1){notice('画像は1枚ずつ選んでください');return;}load(e.dataTransfer.files[0]);};
function render(){if(!image)return;const [w,h]={'3:4':[900,1200],'4:3':[1200,900],'16:9':[1600,900]}[$('ratio').value];const c=$('preview');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);const a=crop(image.naturalWidth,image.naturalHeight,w/h,Number($('x').value)/100,Number($('y').value)/100);ctx.drawImage(image,a.sx,a.sy,a.sw,a.sh,0,0,w,h);$('download').disabled=false;}['ratio','x','y'].forEach(id=>$(id).oninput=render);
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=()=>{if(image)$('preview').toBlob(b=>{if(b)download(b,'fieldrise-photo-'+$('ratio').value.replace(':','x')+'.jpg');else notice('画像出力に失敗しました');},'image/jpeg',.92);};
$('generate').onclick=()=>{const out=generate($('genre').value,$('context').value,$('purpose').value,song());Object.entries(out).forEach(([k,v])=>$(k).value=v);notice('投稿文を生成しました。内容に合わせて編集してください。');};
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const k=b.dataset.copy,text=k==='song'?song().title:k==='caption'?$('description').value+'\n'+$('tags').value:$('title').value;try{await navigator.clipboard.writeText(text);notice('コピーしました');}catch{notice('コピーできません。該当する入力欄から手動コピーしてください');}});
$('record').onclick=()=>{try{if(!image)throw Error('画像を選択してください');const postUrl=safeUrl($('postUrl').value);const postedAt=$('postedAt').value;if(Boolean(postUrl)!==Boolean(postedAt))throw Error('公開記録には投稿URLと投稿日時の両方を入力してください');for(const id of ['views','uses'])if($(id).value&&!/^[0-9]+$/.test($(id).value))throw Error('数値は0以上の整数にしてください');records.push({preparedAt:new Date().toISOString(),postedAt,platform:'TikTok',song:song().title,artist:song().artist,music:{...song()},image:imageName,ratio:$('ratio').value,cropPosition:{x:$('x').value,y:$('y').value},title:$('title').value,description:$('description').value,hashtags:$('tags').value,postUrl,views:$('views').value,uses:$('uses').value,revenue:$('revenue').value,state:postUrl?'published_owner_reported':'prepared',revenueVerified:false});if(persist())notice('記録を端末に保存しました。投稿・収益の自動確認はしていません。');info();}catch(e){notice(e.message);}};
$('json').onclick=()=>download(new Blob([JSON.stringify({schemaVersion:1,songs,records},null,2)],{type:'application/json'}),'fieldrise-photo-records.json');$('csv').onclick=()=>download(new Blob([csv(records)],{type:'text/csv;charset=utf-8'}),'fieldrise-photo-records.csv');
