import {music,record,migrate,merge,preflight,csv2,VERSION} from './data.mjs';
import {seed,crop,generate,safeUrl,csv} from './core.mjs';
const $=id=>document.getElementById(id), key='fieldrise-photo-v1';let songs=[music(seed)],records=[],image=null,imageName='',loadSeq=0;
function notice(s){$('status').textContent=s;}try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.songs)&&Array.isArray(saved.records)){const valid=migrate(saved);songs=valid.songs;records=valid.records;}}catch{notice('保存データを読み込めませんでした。新規状態で開始します。');}
function persist(){try{localStorage.setItem(key,JSON.stringify({schemaVersion:VERSION,songs,records}));return true;}catch{notice('端末保存に失敗しました。JSON出力でバックアップしてください。');return false;}}
function song(){return songs[Number($('songs').value)]||seed;}function list(){const sel=$('songs');sel.replaceChildren();songs.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.title+' / '+s.artist;sel.append(o);});info();}function info(){$('songInfo').textContent=song().duration+' · '+song().distribution+' · '+song().search+' · 音源一致：'+(song().match||'未確認');const link=$('officialSound');link.hidden=!song().soundUrl;if(song().soundUrl)link.href=song().soundUrl;$('history').textContent='保存記録：'+records.length+'件（準備と公開確認を区別）';}list();$('songs').onchange=info;
function musicInput(){return music({id:song().id,title:$('songTitle').value,artist:$('artist').value,duration:$('duration').value,isrc:$('isrc').value,distribution:$('distribution').value,search:$('search').value,soundUrl:$('soundUrl').value,...Object.fromEntries(['soundOnId','tiktokId','match','reviewer','verifiedAt','method','evidence'].map(k=>[k,$(k).value]))});}
$('songForm').onsubmit=e=>{e.preventDefault();try{const m=musicInput();m.id=crypto.randomUUID();songs.push(m);list();$('songs').value=songs.length-1;info();persist();notice('楽曲を登録しました');}catch(e){notice(e.message);}};
$('editSong').onclick=()=>{const m=song();for(const k of ['artist','duration','isrc','soundUrl','soundOnId','tiktokId','match','reviewer','verifiedAt','method','evidence'])$(k).value=m[k]||'';$('songTitle').value=m.title;notice('選択楽曲を編集欄に表示しました。配信状況も指定して更新してください。');};
$('updateSong').onclick=()=>{try{songs[Number($('songs').value)||0]=musicInput();const i=$('songs').value;list();$('songs').value=i;info();persist();notice('楽曲を更新しました。過去投稿の確認スナップショットは保持します。');}catch(e){notice(e.message);}};
async function load(file){const seq=++loadSeq;image=null;$('download').disabled=true;$('preview').getContext('2d').clearRect(0,0,$('preview').width,$('preview').height);try{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>20*1024*1024)throw Error('JPG・PNG・WebP、20 MiB以下の画像を選んでください');const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const valid=file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:file.type==='image/png'?bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!valid)throw Error('画像形式とファイル内容が一致しません');const url=URL.createObjectURL(file);const img=new Image();try{img.src=url;await img.decode();}finally{URL.revokeObjectURL(url);}if(seq!==loadSeq)return;if(img.naturalWidth*img.naturalHeight>24000000||img.naturalWidth>10000||img.naturalHeight>10000)throw Error('画像が大きすぎます。24百万画素・各辺10000以下にしてください');image=img;imageName=file.name;$('meta').textContent=file.name+' / '+img.naturalWidth+' × '+img.naturalHeight+' / '+(img.naturalWidth/img.naturalHeight).toFixed(3);render();notice('画像を読み込みました。切り抜き位置を確認してください。');}catch(e){if(seq===loadSeq)notice(e.message);}}
$('image').onchange=e=>load(e.target.files[0]);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length!==1){notice('画像は1枚ずつ選んでください');return;}load(e.dataTransfer.files[0]);};
function render(){if(!image)return;const [w,h]={'3:4':[900,1200],'4:3':[1200,900],'16:9':[1600,900]}[$('ratio').value];const c=$('preview');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);const a=crop(image.naturalWidth,image.naturalHeight,w/h,Number($('x').value)/100,Number($('y').value)/100);ctx.drawImage(image,a.sx,a.sy,a.sw,a.sh,0,0,w,h);$('download').disabled=false;}['ratio','x','y'].forEach(id=>$(id).oninput=render);
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=()=>{if(image)$('preview').toBlob(b=>{if(b)download(b,'fieldrise-photo-'+$('ratio').value.replace(':','x')+'.jpg');else notice('画像出力に失敗しました');},'image/jpeg',.92);};
$('generate').onclick=()=>{const out=generate($('genre').value,$('context').value,$('purpose').value,song());Object.entries(out).forEach(([k,v])=>$(k).value=v);notice('投稿文を生成しました。内容に合わせて編集してください。');};
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const k=b.dataset.copy,text=k==='song'?song().title:k==='caption'?$('description').value+'\n'+$('tags').value:$('title').value;try{await navigator.clipboard.writeText(text);notice('コピーしました');}catch{notice('コピーできません。該当する入力欄から手動コピーしてください');}});
function check(){const result=preflight({image:Boolean(image),title:$('title').value,description:$('description').value,selected:Boolean(song()),distribution:$('distributionChecked').checked,match:song().match,final:$('finalSoundChecked').checked,override:$('override').value});$('preflight').textContent=result.label+' / '+result.warnings.join('・');return result;}
$('checkReady').onclick=check;
function recordInput(old={}){if(!check().mayProceed)throw Error('投稿前確認が必要です。不一致は準備完了にできません');return record({...old,id:old.id||crypto.randomUUID(),preparedAt:old.preparedAt||new Date().toISOString(),image:imageName||old.image,song:song().title,artist:song().artist,music:{...song()},match:song().match,distributionChecked:$('distributionChecked').checked,finalSoundChecked:$('finalSoundChecked').checked,...Object.fromEntries(['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','override','notes'].map(k=>[k,$(k==='hashtags'?'tags':k).value]))});}
function historyList(){const sel=$('recordSelect');sel.replaceChildren();records.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.id+' / '+r.song+' / '+r.match+' / '+r.revenueStatus;sel.append(o);});info();}
$('record').onclick=()=>{try{if(!image)throw Error('画像を選択してください');records.push(recordInput());persist();historyList();notice('準備記録を保存しました。収益と公開は自動確認していません。');}catch(e){notice(e.message);}};
$('editRecord').onclick=()=>{const r=records[Number($('recordSelect').value)];if(!r){notice('記録を選択してください');return;}for(const k of ['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','override','notes'])$(k==='hashtags'?'tags':k).value=r[k]??'';$('distributionChecked').checked=r.distributionChecked;$('finalSoundChecked').checked=r.finalSoundChecked;notice('記録を編集できます。音源スナップショットは更新しても保持します。');};
$('updateRecord').onclick=()=>{try{const i=Number($('recordSelect').value),old=records[i];if(!old)throw Error('記録を選択してください');records[i]=record({...old,...Object.fromEntries(['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','notes'].map(k=>[k,$(k==='hashtags'?'tags':k).value]))});persist();historyList();notice('記録を更新しました。音源確認履歴は保持しました。');}catch(e){notice(e.message);}};
$('deleteRecord').onclick=()=>{if(!$('deleteConsent').checked){notice('バックアップと削除確認が必要です');return;}const i=Number($('recordSelect').value);if(!records[i])return;records.splice(i,1);$('deleteConsent').checked=false;persist();historyList();notice('選択記録を削除しました');};
let pending=null;$('importCheck').onclick=async()=>{pending=null;$('importMerge').disabled=true;try{const f=$('importFile').files[0];if(!f||f.size>5*1024*1024)throw Error('5 MiB以下のJSONを選択してください');pending=migrate(JSON.parse(await f.text()));merge({schemaVersion:VERSION,songs,records},pending);$('importSummary').textContent='追加予定：楽曲'+pending.songs.length+'件、記録'+pending.records.length+'件。既存データは上書きしません。';$('importMerge').disabled=false;}catch(e){notice(e.message);}};
$('importMerge').onclick=()=>{try{if(!pending)return;const result=merge({schemaVersion:VERSION,songs,records},pending);songs=result.songs;records=result.records;pending=null;$('importMerge').disabled=true;persist();list();historyList();notice('確認済みバックアップを追加しました');}catch(e){notice(e.message);}};
$('json').onclick=()=>download(new Blob([JSON.stringify({schemaVersion:VERSION,songs,records},null,2)],{type:'application/json'}),'fieldrise-photo-records.json');$('csv').onclick=()=>download(new Blob([csv2(records)],{type:'text/csv;charset=utf-8'}),'fieldrise-photo-records.csv');historyList();
