import {LIMITS,dimensions,filename,admit,move,settings,postSet,zip,headerDimensions} from './batch.mjs';
import {music,record,migrate,merge,preflight,csv2,VERSION} from './data.mjs';
import {seed,crop,generate,safeUrl,csv} from './core.mjs';
const $=id=>document.getElementById(id), key='fieldrise-photo-v1';let songs=[music(seed)],records=[],image=null,imageName='',loadSeq=0,sets=[],photos=[],selectedPhoto=-1,busy=false,activeSetId=null,activeSetMusic=null;
function notice(s){$('status').textContent=s;}try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.songs)&&Array.isArray(saved.records)){const valid=migrate(saved);songs=valid.songs;records=valid.records;sets=valid.sets;}}catch{notice('保存データを読み込めませんでした。新規状態で開始します。');}
function persist(){try{localStorage.setItem(key,JSON.stringify({schemaVersion:VERSION,songs,records,sets}));return true;}catch{notice('端末保存に失敗しました。JSON出力でバックアップしてください。');return false;}}
function song(){if(activeSetMusic)return activeSetMusic;return songs[Number($('songs').value)]||seed;}function list(){const sel=$('songs');sel.replaceChildren();songs.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.title+' / '+s.artist;sel.append(o);});info();}function info(){$('songInfo').textContent=song().duration+' · '+song().distribution+' · '+song().search+' · 音源一致：'+(song().match||'未確認');const link=$('officialSound');link.hidden=!song().soundUrl;if(song().soundUrl)link.href=song().soundUrl;$('history').textContent='保存記録：'+records.length+'件（準備と公開確認を区別）';}list();$('songs').onchange=()=>{activeSetMusic=null;$('finalSoundChecked').checked=false;$('distributionChecked').checked=false;info();};
function musicInput(){return music({id:song().id,title:$('songTitle').value,artist:$('artist').value,duration:$('duration').value,isrc:$('isrc').value,distribution:$('distribution').value,search:$('search').value,soundUrl:$('soundUrl').value,...Object.fromEntries(['soundOnId','tiktokId','match','reviewer','verifiedAt','method','evidence'].map(k=>[k,$(k).value]))});}
$('songForm').onsubmit=e=>{e.preventDefault();try{const m=musicInput();m.id=crypto.randomUUID();songs.push(m);list();$('songs').value=songs.length-1;info();persist();notice('楽曲を登録しました');}catch(e){notice(e.message);}};
$('editSong').onclick=()=>{const m=song();for(const k of ['artist','duration','isrc','soundUrl','soundOnId','tiktokId','match','reviewer','verifiedAt','method','evidence'])$(k).value=m[k]||'';$('songTitle').value=m.title;notice('選択楽曲を編集欄に表示しました。配信状況も指定して更新してください。');};
$('updateSong').onclick=()=>{try{if(activeSetMusic)throw Error('楽曲一覧を選び直してマスターを更新してください。セットの根拠は保持します');songs[Number($('songs').value)||0]=musicInput();$('finalSoundChecked').checked=false;$('distributionChecked').checked=false;const i=$('songs').value;list();$('songs').value=i;info();persist();notice('楽曲を更新しました。過去投稿の確認スナップショットは保持します。');}catch(e){notice(e.message);}};
async function decode(file){admit([],file);const bytes=new Uint8Array(await file.slice(0,256*1024).arrayBuffer());const valid=file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:file.type==='image/png'?bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!valid)throw Error('画像形式とファイル内容が一致しません');headerDimensions(bytes,file.type);const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();}finally{URL.revokeObjectURL(url);}if(img.naturalWidth*img.naturalHeight>LIMITS.pixels||img.naturalWidth>10000||img.naturalHeight>10000)throw Error('24百万画素・各辺10000以下の画像にしてください');return img;}
function canvasBlob(c){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('JPEG生成失敗')),'image/jpeg',.92));}
function paint(c,img,p){const [w,h]=dimensions[p.ratio];c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);const a=crop(img.naturalWidth,img.naturalHeight,w/h,p.x/100,p.y/100);ctx.drawImage(img,a.sx,a.sy,a.sw,a.sh,0,0,w,h);}
function redrawList(){$('photoList').replaceChildren();$('photoCount').textContent=photos.length+'枚 / 35枚（元画像再選択待ち '+photos.filter(p=>!p.file).length+'枚）';photos.forEach((p,i)=>{const row=document.createElement('div');row.className='photo-card';if(p.thumb){const img=document.createElement('img');img.src=p.thumb;img.alt=p.name;row.append(img);}const text=document.createElement('p');text.textContent=(i+1)+'. '+p.name+(p.file?'':'（再選択が必要）');row.append(text);for(const [label,action] of [['選択',()=>selectPhoto(i)],['↑',()=>reorder(i,-1)],['↓',()=>reorder(i,1)],['削除',()=>removePhoto(i)]]){const b=document.createElement('button');b.textContent=label;b.disabled=busy;b.onclick=action;row.append(b);}$('photoList').append(row);});}
function revokeThumb(p){if(p.thumb)URL.revokeObjectURL(p.thumb);}
async function loadMany(files){if(busy){notice('処理中です。終了後に操作してください');return;}busy=true;const errors=[];for(const f of Array.from(files).slice(0,70)){try{const missing=photos.find(p=>!p.file&&p.name===f.name&&p.size===f.size&&p.lastModified===(f.lastModified||0));if(!missing)admit(photos,f);const img=await decode(f),c=document.createElement('canvas');c.width=160;c.height=120;c.getContext('2d').drawImage(img,0,0,160,120);const thumb=URL.createObjectURL(await canvasBlob(c));const entry={id:crypto.randomUUID(),name:f.name,size:f.size,lastModified:f.lastModified||0,...settings({ratio:$('ratio').value}),file:f,thumb,width:img.naturalWidth,height:img.naturalHeight};if(missing){Object.assign(missing,{file:f,thumb,width:entry.width,height:entry.height});}else photos.push(entry);image=img;imageName=f.name;selectedPhoto=photos.indexOf(missing||entry);$('x').value=photos[selectedPhoto].x;$('y').value=photos[selectedPhoto].y;$('ratio').value=photos[selectedPhoto].ratio;render();}catch(e){errors.push(f.name+': '+e.message);}}if(files.length>70)errors.push('1回の受付は70候補まで。セットには最大35枚です');busy=false;$('photoErrors').textContent=errors.join('\n');redrawList();notice(errors.length?'一部画像を拒否しました。個別エラーを確認してください':'画像を読み込みました');if(!photos.length){image=null;$('download').disabled=true;}}
async function selectPhoto(i){if(busy)return;const p=photos[i];selectedPhoto=i;$('ratio').value=p.ratio;$('x').value=p.x;$('y').value=p.y;imageName=p.name;if(!p.file){image=null;$('download').disabled=true;notice('元画像を再選択してください');return;}busy=true;try{image=await decode(p.file);render();}catch(e){image=null;notice(e.message);}finally{busy=false;redrawList();}}
function reorder(i,d){if(busy)return;const id=photos[selectedPhoto]?.id;photos=move(photos,i,d);selectedPhoto=photos.findIndex(p=>p.id===id);redrawList();}
function removePhoto(i){if(busy)return;revokeThumb(photos[i]);photos.splice(i,1);selectedPhoto=-1;image=null;$('download').disabled=true;$('preview').getContext('2d').clearRect(0,0,$('preview').width,$('preview').height);redrawList();if(photos.length)selectPhoto(0);}
$('image').onchange=e=>loadMany(e.target.files);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();return loadMany(e.dataTransfer.files);};
function render(){if(!image||!photos[selectedPhoto])return;const p=photos[selectedPhoto];Object.assign(p,settings({ratio:$('ratio').value,x:$('x').value,y:$('y').value}));paint($('preview'),image,p);$('meta').textContent=p.name+' / '+image.naturalWidth+' × '+image.naturalHeight+' / '+(image.naturalWidth>=image.naturalHeight?'横向き':'縦向き')+' / 比率 '+(image.naturalWidth/image.naturalHeight).toFixed(3);$('download').disabled=false;}['ratio','x','y'].forEach(id=>$(id).oninput=()=>{if(!busy)render();});
$('applyRatio').onclick=()=>{if(busy)return;photos.forEach(p=>p.ratio=$('ratio').value);render();redrawList();notice('全写真へ共通比率を適用しました');};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=async()=>{if(busy||!image)return;try{download(await canvasBlob($('preview')),filename(selectedPhoto));notice('保存処理を開始しました。ブラウザのダウンロード結果を確認してください');}catch(e){notice(e.message+'。選択写真で再実行してください');}};
$('downloadAll').onclick=async()=>{if(busy)return;if(!photos.length||photos.some(p=>!p.file)){notice('全写真の元画像を選択してください');return;}busy=true;$('downloadAll').disabled=true;const entries=[],errors=[];let total=0;for(let i=0;i<photos.length;i++){try{const img=await decode(photos[i].file),c=document.createElement('canvas');paint(c,img,photos[i]);const blob=await canvasBlob(c);total+=blob.size;if(total>LIMITS.zip)throw Error('出力合計50 MiB超過');entries.push({name:filename(i),blob});}catch(e){errors.push(filename(i)+': '+e.message);}}try{if(entries.length)download(await zip(entries),'FieldRise_TikTok_Photos.zip');notice(errors.length?'一部写真が失敗しました。成功分のみZIPを作成。失敗写真を選択して個別保存してください':'ZIP保存処理を開始しました。端末への保存完了はブラウザで確認してください');$('photoErrors').textContent=errors.join('\n');}catch(e){notice('ZIP生成失敗：'+e.message+'。各写真を選択して個別保存してください');}finally{busy=false;$('downloadAll').disabled=false;redrawList();}};
$('generate').onclick=()=>{const out=generate($('genre').value,$('context').value,$('purpose').value,song());Object.entries(out).forEach(([k,v])=>$(k).value=v);notice('投稿文を生成しました。内容に合わせて編集してください。');};
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const k=b.dataset.copy,text=k==='song'?song().title:k==='caption'?$('description').value+'\n'+$('tags').value:$('title').value;try{await navigator.clipboard.writeText(text);notice('コピーしました');}catch{notice('コピーできません。該当する入力欄から手動コピーしてください');}});
function check(){const result=preflight({image:photos.length>0&&photos.every(p=>p.file),title:$('title').value,description:$('description').value,selected:Boolean(song()),distribution:$('distributionChecked').checked,match:song().match,final:$('finalSoundChecked').checked,override:$('override').value});$('preflight').textContent=result.label+' / '+result.warnings.join('・');return result;}
$('checkReady').onclick=check;
function recordInput(old={}){if(!check().mayProceed)throw Error('投稿前確認が必要です。不一致は準備完了にできません');return record({...old,id:old.id||crypto.randomUUID(),photoSetId:activeSetId||'',photoCount:photos.length,preparedAt:old.preparedAt||new Date().toISOString(),image:imageName||old.image,song:song().title,artist:song().artist,music:{...song()},match:song().match,distributionChecked:$('distributionChecked').checked,finalSoundChecked:$('finalSoundChecked').checked,...Object.fromEntries(['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','override','notes'].map(k=>[k,$(k==='hashtags'?'tags':k).value]))});}
function historyList(){const sel=$('recordSelect');sel.replaceChildren();records.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.id+' / '+r.song+' / '+r.match+' / '+r.revenueStatus;sel.append(o);});info();}
$('record').onclick=()=>{try{if(!image)throw Error('画像を選択してください');records.push(recordInput());persist();historyList();notice('準備記録を保存しました。収益と公開は自動確認していません。');}catch(e){notice(e.message);}};
$('editRecord').onclick=()=>{const r=records[Number($('recordSelect').value)];if(!r){notice('記録を選択してください');return;}for(const k of ['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','override','notes'])$(k==='hashtags'?'tags':k).value=r[k]??'';$('distributionChecked').checked=r.distributionChecked;$('finalSoundChecked').checked=r.finalSoundChecked;notice('記録を編集できます。音源スナップショットは更新しても保持します。');};
$('updateRecord').onclick=()=>{try{const i=Number($('recordSelect').value),old=records[i];if(!old)throw Error('記録を選択してください');records[i]=record({...old,...Object.fromEntries(['title','description','hashtags','postUrl','postedAt','views','likes','comments','shares','uses','revenue','revenueStatus','revenueAmount','notes'].map(k=>[k,$(k==='hashtags'?'tags':k).value]))});persist();historyList();notice('記録を更新しました。音源確認履歴は保持しました。');}catch(e){notice(e.message);}};
$('deleteRecord').onclick=()=>{if(!$('deleteConsent').checked){notice('バックアップと削除確認が必要です');return;}const i=Number($('recordSelect').value);if(!records[i])return;records.splice(i,1);$('deleteConsent').checked=false;persist();historyList();notice('選択記録を削除しました');};
let pending=null;$('importCheck').onclick=async()=>{pending=null;$('importMerge').disabled=true;try{const f=$('importFile').files[0];if(!f||f.size>5*1024*1024)throw Error('5 MiB以下のJSONを選択してください');pending=migrate(JSON.parse(await f.text()));merge({schemaVersion:VERSION,songs,records,sets},pending);$('importSummary').textContent='追加予定：楽曲'+pending.songs.length+'件、記録'+pending.records.length+'件、セット'+pending.sets.length+'件。既存データは上書きしません。';$('importMerge').disabled=false;}catch(e){notice(e.message);}};
$('importMerge').onclick=()=>{try{if(!pending)return;const result=merge({schemaVersion:VERSION,songs,records,sets},pending);songs=result.songs;records=result.records;sets=result.sets;setList();pending=null;$('importMerge').disabled=true;persist();list();historyList();notice('確認済みバックアップを追加しました');}catch(e){notice(e.message);}};
$('json').onclick=()=>download(new Blob([JSON.stringify({schemaVersion:VERSION,songs,records,sets},null,2)],{type:'application/json'}),'fieldrise-photo-records.json');$('csv').onclick=()=>download(new Blob([csv2(records)],{type:'text/csv;charset=utf-8'}),'fieldrise-photo-records.csv');historyList();

function setList(){const sel=$('setSelect');sel.replaceChildren();sets.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(s.name||s.id)+' / '+s.photoCount+'枚 / '+(s.ready?'準備完了（保存時）':'未完了');sel.append(o);});}
function captureSet(old={}){const state=check();return postSet({id:old.id||crypto.randomUUID(),name:$('setName').value,createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),photos:photos.map(p=>({id:p.id,name:p.name,size:p.size,lastModified:p.lastModified,ratio:p.ratio,x:p.x,y:p.y})),music:music(song()),title:$('title').value,description:$('description').value,hashtags:$('tags').value,override:$('override').value,distributionChecked:$('distributionChecked').checked,finalSoundChecked:$('finalSoundChecked').checked,ready:state.ready});}
$('saveSet').onclick=()=>{if(busy)return;try{const s=captureSet();sets.push(s);activeSetId=s.id;persist();setList();$('setStatus').textContent='セット保存：'+(s.ready?'準備完了':'未完了')+'。画像本体は保存しません。';}catch(e){notice(e.message);}};
$('updateSet').onclick=()=>{if(busy)return;try{const i=sets.findIndex(s=>s.id===activeSetId);if(i<0)throw Error('セットを再表示してから更新してください');sets[i]=captureSet(sets[i]);persist();setList();notice('再表示中のセットを更新しました');}catch(e){notice(e.message);}};
$('loadSet').onclick=()=>{if(busy)return;const s=sets[Number($('setSelect').value)];if(!s)return;photos.forEach(revokeThumb);photos=s.photos.map(p=>({...p,file:null,thumb:null}));selectedPhoto=-1;image=null;imageName='';activeSetId=s.id;activeSetMusic=s.music;for(const k of ['title','description','override'])$(k).value=s[k];$('tags').value=s.hashtags;$('setName').value=s.name;$('distributionChecked').checked=s.distributionChecked;$('finalSoundChecked').checked=false;$('download').disabled=true;$('preview').getContext('2d').clearRect(0,0,$('preview').width,$('preview').height);redrawList();info();check();$('setStatus').textContent='画像再選択待ち。保存時の音源根拠を保持。Studio最終音源は再確認してください。';};
$('deleteSet').onclick=()=>{if(busy)return;if(!$('deleteSetConsent').checked){notice('セット削除の確認が必要です');return;}const i=Number($('setSelect').value);if(!sets[i])return;if(sets[i].id===activeSetId)activeSetId=null;sets.splice(i,1);$('deleteSetConsent').checked=false;persist();setList();notice('セットを削除しました');};
$('reusePrevious').onclick=()=>{if(busy||!sets.length)return;const s=sets[sets.length-1];$('title').value=s.title;$('description').value=s.description;$('tags').value=s.hashtags;const ratio=s.photos[0]?.ratio||'3:4';$('ratio').value=ratio;photos.forEach(p=>p.ratio=ratio);render();notice('前回の文章と共通比率を呼び出しました。音源確認は流用しません。');};
setList();redrawList();
