import {test} from 'node:test';import assert from 'node:assert/strict';import {admit,move,settings,filename,zip,crc32,postSet,LIMITS,headerDimensions} from '../automation/sns_auto_posting/tiktok/photo/batch.mjs';import {migrate,merge} from '../automation/sns_auto_posting/tiktok/photo/data.mjs';import {seed} from '../automation/sns_auto_posting/tiktok/photo/core.mjs';
const photo={id:'a',name:'a.png',size:100,lastModified:0,ratio:'3:4',x:30,y:60};const set=()=>({id:'s1',name:'set',createdAt:'2026-10-10T10:00:00Z',updatedAt:'2026-10-10T10:00:00Z',photos:[photo],music:seed,title:'t',description:'d',hashtags:'',ready:true});
test('batch count and file/total limits',()=>{admit([],{type:'image/png',size:100});assert.throws(()=>admit(Array(35).fill(photo),{type:'image/png',size:100}));assert.throws(()=>admit([],{type:'text/plain',size:100}));assert.throws(()=>admit([],{type:'image/png',size:LIMITS.file+1}));assert.throws(()=>admit(Array(5).fill({...photo,size:LIMITS.file}),{type:'image/png',size:1}))});
test('reorder nonmutating and crop settings',()=>{const a=[1,2,3];assert.deepEqual(move(a,0,1),[2,1,3]);assert.deepEqual(a,[1,2,3]);assert.deepEqual(move(a,0,-1),a);assert.equal(settings({ratio:'16:9',x:10,y:80}).x,10);assert.throws(()=>settings({x:101}));assert.throws(()=>settings({ratio:'bad'}))});
test('numbered unique output names',()=>{assert.equal(filename(0),'FieldRise_TikTok_001.jpg');assert.equal(filename(34),'FieldRise_TikTok_035.jpg');assert.equal(new Set(Array.from({length:35},(_,i)=>filename(i))).size,35)});
test('ZIP structure and CRC',async()=>{assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926);const b=await zip([{name:filename(0),blob:new Blob(['abc'])},{name:filename(1),blob:new Blob(['def'])}]);const bytes=new Uint8Array(await b.arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(bytes.length-14,true),2);assert.equal(v.getUint32(14,true),crc32(new TextEncoder().encode('abc')));await assert.rejects(()=>zip([{name:'../bad',blob:new Blob(['a'])}]))});
test('set metadata only, unknown never ready, duplicates rejected',()=>{const a=postSet({...set(),photos:[{...photo,file:'raw image'}]});assert.equal(a.ready,false);assert.equal(a.photos[0].file,undefined);assert.throws(()=>postSet({...set(),photos:[photo,photo]}));assert.throws(()=>postSet({...set(),updatedAt:'bad'}))});
test('v1/v2 migration and v3 set import/merge preserve snapshots',()=>{const a=migrate({schemaVersion:2,songs:[seed],records:[]});assert.deepEqual(a.sets,[]);const b=migrate({schemaVersion:3,songs:[{...seed,title:'other'}],records:[],sets:[set()]});assert.equal(b.sets[0].music.match,'未確認');assert.equal(merge(a,b).sets.length,1);assert.throws(()=>merge(b,b))});

test('header preflight rejects oversized images before decoding',()=>{const b=new Uint8Array(24),v=new DataView(b.buffer);v.setUint32(16,1600);v.setUint32(20,900);assert.equal(headerDimensions(b,'image/png').w,1600);v.setUint32(16,100000);assert.throws(()=>headerDimensions(b,'image/png'));assert.throws(()=>headerDimensions(new Uint8Array(4),'image/png'));});
