import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {studioSound,postSet} from '../automation/sns_auto_posting/tiktok/photo/batch.mjs';
import {migrate,music} from '../automation/sns_auto_posting/tiktok/photo/data.mjs';
import {duplicate,transition} from '../automation/sns_auto_posting/tiktok/photo/workflow.mjs';
const expected={id:'cafe-one',title:'cafe',artist:'Runa-Girl8215',duration:'0:59'};
const confirmed={state:'確認済み',observedTitle:'cafe',observedArtist:'Runa-Girl8215',observedDuration:'00:59',jacket:'本人比較したジャケットの識別メモ',release:'SoundOnのリリース・分割1を本人確認',ownerCompared:true,reviewer:'検証用確認者',verifiedAt:'2026-10-10T17:00:00+09:00',draftRetained:true,draftVerifiedAt:'2026-10-10T17:02:00+09:00'};
const base={id:'set-test',name:'Test',createdAt:'2026-10-10T00:00:00Z',updatedAt:'2026-10-10T00:00:00Z',photos:[],music:music(expected),title:'',description:''};
test('artist-first keyword and five explicit comparison states',()=>{assert.equal(studioSound({},expected).searchKeyword,'Runa-Girl8215');for(const state of ['未確認','候補あり','確認済み','不一致','利用不可'])assert.equal(studioSound(state==='確認済み'?confirmed:{state},expected).state,state);assert.throws(()=>studioSound({state:'auto'},expected));});
test('same title alone never confirms split releases or another artist/duration',()=>{assert.throws(()=>studioSound({state:'確認済み',observedTitle:'cafe'},expected));for(const patch of [{observedArtist:'other'},{observedDuration:'1:59'},{release:''},{jacket:''},{ownerCompared:false},{reviewer:''},{verifiedAt:''}])assert.throws(()=>studioSound({...confirmed,...patch},expected));});
test('draft retention requires verified owner comparison and reedit date',()=>{assert.equal(studioSound(confirmed,expected).draftRetained,true);assert.throws(()=>studioSound({...confirmed,state:'候補あり'},expected));assert.throws(()=>studioSound({...confirmed,draftVerifiedAt:''},expected));});
test('set save reload preserves comparison without changing distribution match or IDs',()=>{const input={schemaVersion:6,songs:[base.music],records:[],sets:[{...base,studioSound:confirmed}]};const restored=migrate(JSON.parse(JSON.stringify(migrate(input))));assert.equal(restored.sets[0].id,base.id);assert.equal(restored.sets[0].studioSound.state,'確認済み');assert.equal(restored.sets[0].studioSound.expectedDuration,'0:59');assert.equal(restored.sets[0].studioSound.draftRetained,true);assert.equal(restored.sets[0].music.match,'未確認');assert.equal(restored.sets[0].ready,false);});
test('v1-v6 old sets retain contents without invented Studio comparison',()=>{for(let v=1;v<=6;v++){const restored=migrate({schemaVersion:v,songs:[base.music],records:[],sets:[base]});assert.equal(restored.sets[0].studioSound,undefined);assert.equal(restored.sets[0].id,base.id);}});
test('duplicate resets owner comparison and draft evidence without modifying source',()=>{const source=migrate({songs:[base.music],records:[],sets:[{...base,studioSound:confirmed}]}).sets[0];const snapshot=JSON.stringify(source),copy=duplicate(source);assert.equal(copy.studioSound.state,'未確認');assert.equal(copy.studioSound.draftRetained,false);assert.equal(copy.studioSound.verifiedAt,'');assert.equal(JSON.stringify(source),snapshot);});
test('input validation rejects malformed dates, secret-like text and null objects',()=>{assert.throws(()=>studioSound(null,expected));assert.throws(()=>studioSound({...confirmed,verifiedAt:'not-date'},expected));assert.throws(()=>studioSound({notes:'-----BEGIN PRIVATE KEY'},expected));});
test('Japanese handoff guide exposes artist-first copy and no posting endpoint',()=>{const html=fs.readFileSync(new URL('../automation/sns_auto_posting/tiktok/photo/index.html',import.meta.url),'utf8');assert.match(html,/Runa-Girl8215で検索/);assert.match(html,/id="copySearch"/);assert.match(html,/下書き保存/);assert.match(html,/タイトルだけでは同一音源/);const page=fs.readFileSync(new URL('../automation/sns_auto_posting/tiktok/photo/page.mjs',import.meta.url),'utf8');assert.ok(!/fetch\(|XMLHttpRequest/.test(page));});
test('candidate mismatch and unavailable evidence cannot make set ready',()=>{const prepared={...base,photos:[{id:'p',name:'photo.jpg',size:100,ratio:'3:4',x:50,y:50}],music:{...base.music,match:'確認済み',businessUse:'利用可（本人確認）'},title:'Title',description:'Description',ready:true,distributionChecked:true,finalSoundChecked:true};for(const state of ['未確認','候補あり','不一致','利用不可'])assert.equal(postSet({...prepared,studioSound:{state,notes:'本人の確認待ち'}}).ready,false);});

test('ready and planned transitions require draft reedit retention without breaking legacy import',()=>{const source={...base,ready:true,distributionChecked:true,finalSoundChecked:true,music:{...base.music,match:'確認済み',businessUse:'利用可（本人確認）'},studioSound:{...confirmed,draftRetained:false,draftVerifiedAt:''}};assert.throws(()=>transition(source,{status:'準備完了'}),/下書き/);assert.throws(()=>transition(source,{status:'投稿予定',scheduledAt:'2026-10-11T10:00:00Z'}),/下書き/);assert.equal(transition({...source,studioSound:confirmed},{status:'準備完了'}).status,'準備完了');});
