import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {migrate} from '../automation/sns_auto_posting/tiktok/photo/data.mjs';import {seed} from '../automation/sns_auto_posting/tiktok/photo/core.mjs';
const nodes=new Map();function el(id){if(!nodes.has(id))nodes.set(id,{value:'',checked:false,disabled:false,children:[],replaceChildren(){this.children=[]},append(v){this.children.push(v)},getContext(){return {clearRect(){}}}});return nodes.get(id);}
globalThis.document={getElementById:el,querySelectorAll:()=>[],createElement:()=>({value:'',textContent:'',children:[],append(v){this.children.push(v)},click(){}})};globalThis.confirm=()=>true;
const song={...seed,id:'test-song'},now='2026-10-10T01:00:00Z';
const fixture=migrate({schemaVersion:6,songs:[song],records:[],sets:Array.from({length:9},(_,i)=>({id:'existing-'+i,name:'Same name',createdAt:now,updatedAt:now,music:song,language:'en',category:'ファッション紹介',status:'下書き',title:i<5?'':'Synthetic title',description:i<5?'':'Synthetic manual English',photos:i<5?[]:Array.from({length:3},(_,j)=>({id:'p'+j,name:'sample'+j+'.jpg',size:100,lastModified:1,ratio:'3:4',x:50,y:50}))}))});
let stored=JSON.stringify(fixture),writes=0,fail=false,reenter=false;globalThis.localStorage={getItem:()=>stored,setItem:(k,v)=>{if(reenter){assert.equal(el('saveSet').disabled,true);assert.equal(el('saveCurrent').disabled,true);reenter=false;el('saveSet').onclick();}if(fail)throw Error('quota');writes++;stored=v;}};el('genre').value='ファッション紹介';el('captionLength').value='標準';await import('../automation/sns_auto_posting/tiktok/photo/page.mjs');
test('existing nine names IDs metadata and snapshots remain untouched on boot and JSON roundtrip',()=>{assert.deepEqual(JSON.parse(stored),fixture);assert.deepEqual(migrate(JSON.parse(stored)),fixture);assert.equal(fixture.sets.filter(s=>s.photoCount===0).length,5);assert.equal(fixture.sets.filter(s=>s.photoCount===3).length,4);assert.equal(writes,0);});
test('trimmed same-name guard retains all nine and offers explicit ID selection',()=>{el('setName').value='  Same name  ';el('saveSet').onclick();assert.equal(writes,0);assert.equal(el('sameNameSets').children.length,9);assert.match(el('setStatus').textContent,/9件/);assert.deepEqual(JSON.parse(stored),fixture);el('sameNameSets').children[5].onclick();assert.equal(writes,0);assert.equal(el('description').value,'Synthetic manual English');assert.match(el('setStatus').textContent,/読み込み完了.*保存は実行していません/);assert.match(el('editorState').textContent,/existing-5/);});
test('new one-operation save plus rapid/reentrant clicks creates exactly one row',()=>{el('newSet').onclick();el('setName').value='  New unique  ';reenter=true;el('saveSet').onclick();el('saveSet').onclick();el('saveCurrent').onclick();assert.equal(JSON.parse(stored).sets.length,10);assert.equal(writes,1);assert.equal(JSON.parse(stored).sets.at(-1).name,'New unique');assert.deepEqual(JSON.parse(stored).sets.slice(0,9),fixture.sets);});
test('open is read-only, update retains ID and touches only selected row; repeated unchanged update no write',()=>{el('setSelect').value='5';el('loadSet').onclick();const before=JSON.parse(stored),count=writes;el('description').value='Edited English';el('description').oninput();assert.match(el('editorState').textContent,/未保存変更あり/);el('updateSet').onclick();el('updateSet').onclick();const after=JSON.parse(stored);assert.equal(writes,count+1);assert.equal(after.sets[5].id,'existing-5');assert.equal(after.sets[5].description,'Edited English');assert.deepEqual(after.sets[5].photos,before.sets[5].photos);assert.deepEqual(after.sets.filter((_,i)=>i!==5),before.sets.filter((_,i)=>i!==5));});
test('quota failure leaves stored and in-memory data unchanged; explicit retry updates once',()=>{const before=stored,count=writes;el('description').value='Unstored edit';fail=true;el('updateSet').onclick();assert.equal(stored,before);assert.match(el('setStatus').textContent,/保存失敗.*端末保存未完了/);assert.match(el('editorState').textContent,/未保存変更あり/);fail=false;el('updateSet').onclick();assert.equal(writes,count+1);assert.equal(JSON.parse(stored).sets[5].description,'Unstored edit');});
test('simulated fresh page restores nine plus intended new row without modifying storage',async()=>{const before=stored;await import('../automation/sns_auto_posting/tiktok/photo/page.mjs?set-restart');assert.equal(stored,before);el('setSelect').value='5';el('loadSet').onclick();assert.equal(el('description').value,'Unstored edit');assert.equal(el('language').value,'en');assert.equal(JSON.parse(stored).sets.length,10);});

test('duplicate and existing explicit delete preserve all sets on quota failure',()=>{el('setSelect').value='5';const before=stored;fail=true;el('duplicateSet').onclick();assert.equal(stored,before);el('deleteSetConsent').checked=true;el('deleteSet').onclick();assert.equal(stored,before);assert.equal(el('deleteSetConsent').checked,true);fail=false;el('setSelect').value='5';el('loadSet').onclick();assert.equal(stored,before);assert.match(el('editorState').textContent,/existing-5/);});
