import {test} from 'node:test';import assert from 'node:assert/strict';
import {protectedStorage} from '../automation/sns_auto_posting/tiktok/photo/storage.mjs';
import {migrate} from '../automation/sns_auto_posting/tiktok/photo/data.mjs';
import {seed} from '../automation/sns_auto_posting/tiktok/photo/core.mjs';
const fixture=migrate({schemaVersion:6,songs:[seed],records:[],sets:Array.from({length:10},(_,i)=>({id:'synthetic-'+i,name:'Test',createdAt:'2026-10-10T00:00:00Z',updatedAt:'2026-10-10T00:00:00Z',music:seed,status:'下書き',photos:[]}))});
function env(raw=JSON.stringify(fixture)){let value=raw,fail=false,writes=0;return {storage:{getItem:()=>value,setItem:(k,v)=>{if(fail)throw Error('quota');value=v;writes++;}},raw:()=>value,writes:()=>writes,set:v=>value=v,fail:v=>fail=v};}
test('schema6 ten sets read/write/reload preserves IDs and all fields',()=>{const e=env(),g=protectedStorage(e.storage,'key',migrate);assert.equal(g.read().ok,true);assert.equal(e.writes(),0);assert.equal(g.write(fixture).ok,true);const h=protectedStorage(e.storage,'key',migrate);assert.equal(h.read().ok,true);assert.deepEqual(JSON.parse(e.raw()),fixture);});
test('malformed JSON and unsupported version protect original; revalidation never writes',()=>{for(const raw of ['{bad',JSON.stringify({...fixture,schemaVersion:999})]){const e=env(raw),g=protectedStorage(e.storage,'key',migrate);assert.equal(g.read().ok,false);assert.equal(g.write(fixture).ok,false);assert.equal(e.raw(),raw);assert.equal(e.writes(),0);e.set(JSON.stringify(fixture));assert.equal(g.read().ok,true);assert.equal(e.writes(),0);}});
test('quota failure retains exact original and retry succeeds',()=>{const e=env(),g=protectedStorage(e.storage,'key',migrate);g.read();const before=e.raw();e.fail(true);assert.equal(g.write(fixture).ok,false);assert.equal(e.raw(),before);e.fail(false);assert.equal(g.write(fixture).ok,true);});
test('two tabs stale update blocked without loss; conflict also blocks backup write',()=>{const e=env(),a=protectedStorage(e.storage,'key',migrate),b=protectedStorage(e.storage,'key',migrate);a.read();b.read();const next=structuredClone(fixture);next.sets[0].name='Changed in A';assert.equal(a.write(next).ok,true);const before=e.raw();assert.equal(b.changed(),true);assert.equal(b.write(fixture).ok,false);assert.equal(b.write(fixture).ok,false);assert.equal(e.raw(),before);});
test('storage access denial is a protected read failure',()=>{const g=protectedStorage({getItem(){throw Object.assign(Error(),{name:'SecurityError'});},setItem(){throw Error('must not write');}},'key',migrate);assert.equal(g.read().ok,false);assert.equal(g.write(fixture).ok,false);assert.match(g.state().reason,/アクセス/);});
