import {test} from 'node:test';import assert from 'node:assert/strict';
const nodes=new Map();function el(id){if(!nodes.has(id))nodes.set(id,{value:'',disabled:false,textContent:'',files:[],children:[],replaceChildren(){this.children=[]},append(v){this.children.push(v)},getContext(){return {clearRect(){},fillRect(){},drawImage(...args){nodes.set('draw',args)}}},toBlob(cb){cb(new Blob(['image']))}});return nodes.get(id)}
globalThis.confirm=()=>true;globalThis.document={getElementById:el,querySelectorAll:()=>['title','description','caption','song','tags'].map(k=>{const b=el('copy_'+k);b.dataset={copy:k};return b;}),createElement:(tag)=>tag==='canvas'?el('temporaryCanvas'):{click(){},value:'',textContent:'',children:[],append(v){this.children.push(v)}}};Object.defineProperty(globalThis,'navigator',{value:{clipboard:{writeText:async text=>{el('clipboard').textContent=text}}},configurable:true});const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)};globalThis.Image=class{naturalWidth=1600;naturalHeight=900;async decode(){}};
el('ratio').value='3:4';el('x').value='50';el('y').value='50';el('genre').value='カフェ・リラックス';el('purpose').value='楽曲を紹介';await import('../automation/sns_auto_posting/tiktok/photo/page.mjs');
test('invalid file fails safely',async()=>{assert.equal(el('language').value,'en');el('language').value='ja';await el('image').onchange({target:{files:[new Blob(['bad'],{type:'image/png'})]}});assert.equal(el('download').disabled,true);assert.match(el('photoErrors').textContent,/一致しません/)});
test('image processing, generated text and preparation storage',async()=>{const png=new Blob([new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,6,64,0,0,3,132])],{type:'image/png'});png.name='sample.png';await el('image').onchange({target:{files:[png]}});assert.equal(el('download').disabled,false);assert.equal(el('preview').width,900);assert.equal(el('preview').height,1200);assert.equal(nodes.get('draw').length,9);el('generate').onclick();assert.match(el('description').value,/cafe/);el('override').value='社長判断：音源確認は公開前に行う';el('revenueStatus').value='未確認';el('record').onclick();const saved=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(saved.records[0].state,'prepared');assert.equal(saved.records[0].revenueVerified,false);assert.equal(saved.records[0].music.isrc,'');assert.equal(saved.records[0].image,'sample.png');});
test('incomplete public record rejected',()=>{el('postUrl').value='https://www.tiktok.com/@x/video/1';el('record').onclick();assert.match(el('status').textContent,/両方/);assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).records.length,1)});

test('record edit and explicit deletion',()=>{el('postUrl').value='';el('notes').value='更新メモ';el('updateRecord').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).records[0].notes,'更新メモ');el('deleteRecord').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).records.length,1);el('deleteConsent').checked=true;el('deleteRecord').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).records.length,0)});
test('import preview then explicit merge',async()=>{el('importFile').files=[{size:100,text:async()=>JSON.stringify({schemaVersion:1,songs:[{title:'別曲',artist:'Runa-Girl8215',duration:'1:00'}],records:[]})}];await el('importCheck').onclick();assert.equal(el('importMerge').disabled,false);assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).songs.length,1);el('importMerge').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).songs.length,2)});

function fixture(name){const b=new Blob([new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,6,64,0,0,3,132])],{type:'image/png'});b.name=name;return b;}
test('batch intake, individual rejection and reorder',async()=>{await el('image').onchange({target:{files:[fixture('second.png'),Object.assign(new Blob(['x'],{type:'text/plain'}),{name:'bad.txt'})]}});assert.match(el('photoCount').textContent,/2枚/);assert.match(el('photoErrors').textContent,/bad.txt/);const first=el('photoList').children[0];first.children.find(b=>b.textContent==='↓').onclick();assert.match(el('photoList').children[0].children.find(b=>b.textContent?.includes('second.png')).textContent,/second.png/);el('ratio').value='16:9';el('applyRatio').onclick();assert.equal(el('preview').width,1600);});
test('post set save, restore missing images, update and delete',()=>{el('setName').value='午後のカフェ';el('saveSet').onclick();let saved=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(saved.sets[0].photos.length,2);assert.equal(saved.sets[0].ready,false);assert.equal(saved.sets[0].photos[0].ratio,'16:9');assert.equal(saved.sets[0].photos[0].file,undefined);el('loadSet').onclick();assert.match(el('photoCount').textContent,/再選択待ち 2枚/);assert.equal(el('finalSoundChecked').checked,false);el('setName').value='更新';el('updateSet').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).sets[0].name,'更新');el('deleteSetConsent').checked=true;el('deleteSet').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).sets.length,0);});
test('reselection restores original settings and individual removal',async()=>{await el('image').onchange({target:{files:[fixture('second.png'),fixture('sample.png')]}});assert.match(el('photoCount').textContent,/再選択待ち 0枚/);el('photoList').children[0].children.find(b=>b.textContent==='削除').onclick();assert.match(el('photoCount').textContent,/1枚/);});
test('workflow candidates, reuse, search, duplication and owner publication record',()=>{el('genre').value='旅行・風景';el('captionLength').value='長め';el('generate').onclick();assert.equal(el('captionCandidates').children.length,6);el('captionCandidates').children[3].onclick();assert.match(el('description').value,/風景/);el('setName').value='旅行セット';el('saveSet').onclick();el('setSelect').value=0;el('setQuery').value='旅行';el('setQuery').oninput();assert.equal(el('setTable').children.length,1);el('reusePrevious').onclick();assert.equal(el('genre').value,'旅行・風景');el('duplicateSet').onclick();let saved=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(saved.sets.length,2);assert.equal(saved.sets[1].finalSoundChecked,false);el('setState').value='投稿予定';el('scheduledAt').value='2026-10-10T20:00';el('changeSetState').onclick();assert.match(el('status').textContent,/必要/);el('setState').value='投稿済み';el('publishedUrl').value='https://www.tiktok.com/@runa_girl8215/photo/12';el('publishedAt').value='2026-10-10T20:00';el('changeSetState').onclick();saved=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(saved.sets[1].status,'投稿済み');assert.equal(saved.sets[1].music.match,'未確認');assert.equal(saved.sets[1].publishedAt,'2026-10-10T11:00:00.000Z');assert.equal(saved.sets[1].statusHistory.length,2);el('newSet').onclick();assert.match(el('photoCount').textContent,/0枚/);});

test('one-click copy uses edited text and handles clipboard rejection',async()=>{el('title').value='編集タイトル';el('description').value='編集説明';el('tags').value='#旅行';await el('copy_title').onclick();assert.equal(el('clipboard').textContent,'編集タイトル');await el('copy_caption').onclick();assert.equal(el('clipboard').textContent,'編集説明\n#旅行');await el('copy_song').onclick();assert.match(el('clipboard').textContent,/cafe/);navigator.clipboard.writeText=async()=>{throw Error('blocked')};await el('copy_title').onclick();assert.match(el('status').textContent,/手動コピー/);});
test('handoff tag copy, hidden-set protection, history reuse and failed-save recovery',async()=>{navigator.clipboard.writeText=async text=>el('clipboard').textContent=text;el('tags').value='#日常';await el('copy_tags').onclick();assert.equal(el('clipboard').textContent,'#日常');el('studioLink').onclick();assert.match(el('handoffInfo').textContent,/cafe/);el('setQuery').value='該当なし';el('setQuery').oninput();assert.equal(el('setTable').children.length,0);const before=JSON.parse(storage.get('fieldrise-photo-v1')).sets.length;el('duplicateSet').onclick();assert.match(el('status').textContent,/選択/);assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).sets.length,before);el('historyQuery').value='';el('historyQuery').oninput();assert.ok(el('contentHistory').children.length>0);el('contentHistory').children[0].children.find(b=>b.textContent==='この文章を再利用').onclick();assert.ok(el('description').value);assert.match(el('repeatWarning').textContent,/同一文面/);const original=localStorage.setItem;localStorage.setItem=()=>{throw Error('quota')};el('setName').value='未保存テスト';el('saveSet').onclick();assert.match(el('storageStatus').textContent,/保存失敗/);assert.match(el('status').textContent,/未保存/);localStorage.setItem=original;el('saveSet').onclick();assert.equal(el('storageStatus').textContent,'端末保存済み');});
test('batch ZIP handoff and JPEG failure recovery in mock canvas',async()=>{await el('image').onchange({target:{files:[fixture('handoff.png')]}});await el('downloadAll').onclick();assert.match(el('status').textContent,/ZIP保存/);const original=el('temporaryCanvas').toBlob;el('temporaryCanvas').toBlob=cb=>cb(null);await el('downloadAll').onclick();assert.match(el('photoErrors').textContent,/JPEG生成失敗/);assert.match(el('status').textContent,/個別保存/);el('temporaryCanvas').toBlob=original;});
test('English new-set default, switching preserves edits, regeneration consent and all English copy modes',async()=>{globalThis.confirm=()=>true;el('newSet').onclick();assert.equal(el('language').value,'en');el('genre').value='カフェ・リラックス';el('purpose').value='日常を共有';el('captionLength').value='標準';el('context').value='Coffee by the window';el('generate').onclick();assert.equal(el('captionStyle').value,'Natural');assert.match(el('description').value,/Coffee/);el('description').value='My edited caption.';el('language').value='ja';el('language').onchange();assert.equal(el('description').value,'My edited caption.');assert.equal(el('captionCandidates').children.length,0);globalThis.confirm=()=>false;el('generate').onclick();assert.equal(el('description').value,'My edited caption.');globalThis.confirm=()=>true;el('language').value='en';el('language').onchange();el('generate').onclick();el('captionCandidates').children[5].onclick();assert.equal(el('captionStyle').value,'Minimal');el('brandTags').checked=true;el('setName').value='English Test';el('saveCurrent').onclick();let data=JSON.parse(storage.get('fieldrise-photo-v1'));const row=data.sets.at(-1);assert.equal(row.language,'en');assert.equal(row.captionStyle,'Minimal');el('loadSet').onclick();assert.equal(el('language').value,'en');assert.equal(el('captionStyle').value,'Minimal');const text=el('description').value;navigator.clipboard.writeText=async text=>el('clipboard').textContent=text;await el('copy_description').onclick();assert.equal(el('clipboard').textContent,text);await el('copy_caption').onclick();assert.equal(el('clipboard').textContent,text+'\n'+el('tags').value);await el('copy_tags').onclick();assert.ok(!/[\p{Script=Han}\p{Script=Hiragana}]/u.test(el('clipboard').textContent));el('duplicateSet').onclick();data=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(data.sets.at(-1).language,'en');assert.equal(data.sets.at(-1).finalSoundChecked,false);});

test('import cancellation and quota failure are atomic, retry completes same validated backup',async()=>{globalThis.confirm=()=>false;const before=storage.get('fieldrise-photo-v1');el('importFile').files=[{size:100,text:async()=>JSON.stringify({songs:[{id:'new-import',title:'New unique song',artist:'Runa-Girl8215',duration:'1:23'}],records:[]})}];await el('importCheck').onclick();el('importMerge').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);globalThis.confirm=()=>true;const original=localStorage.setItem;localStorage.setItem=()=>{throw Error('quota')};el('importMerge').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);assert.match(el('status').textContent,/既存データと画面内データは変更していません/);localStorage.setItem=original;el('importMerge').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).songs.at(-1).id,'new-import');});

test('simulated new page instance restores saved English metadata and immutable snapshots',async()=>{const before=JSON.parse(storage.get('fieldrise-photo-v1'));const i=before.sets.findIndex(s=>s.name==='English Test');assert.ok(i>=0);await import('../automation/sns_auto_posting/tiktok/photo/page.mjs?reload-validation');el('setSelect').value=i;el('loadSet').onclick();assert.equal(el('language').value,before.sets[i].language);assert.equal(el('captionStyle').value,before.sets[i].captionStyle);assert.equal(el('description').value,before.sets[i].description);assert.equal(el('genre').value,before.sets[i].category);assert.equal(el('finalSoundChecked').checked,false);assert.deepEqual(JSON.parse(storage.get('fieldrise-photo-v1')),before);});

 test('ZIP alone: empty rejected, three images with no caption or sound checks export; dimensions, lock, failure and storage isolation',async()=>{
 el('newSet').onclick();await el('downloadAll').onclick();assert.match(el('exportStatus').textContent,/元画像/);
 await el('image').onchange({target:{files:[fixture('one.png'),fixture('two.png'),fixture('three.png')]}});
 el('ratio').value='3:4';el('applyRatio').onclick();el('title').value='';el('description').value='';el('override').value='';el('distributionChecked').checked=false;el('finalSoundChecked').checked=false;
 const before=storage.get('fieldrise-photo-v1'),original=document.createElement,blobs=[],sizes=[];let clicks=0;
 document.createElement=tag=>{if(tag==='canvas'){const c=original(tag);c.toBlob=cb=>{sizes.push([c.width,c.height]);cb(new Blob(['jpeg mock']))};return c;}const a=original(tag);a.click=()=>clicks++;return a;};
 const create=URL.createObjectURL;URL.createObjectURL=b=>{blobs.push(b);return create(b)};
 const first=el('downloadAll').onclick();await el('downloadAll').onclick();await first;
 assert.equal(clicks,1);assert.deepEqual(sizes,[[900,1200],[900,1200],[900,1200]]);assert.equal(blobs.at(-1).type,'application/zip');assert.match(el('exportStatus').textContent,/画像3枚/);assert.match(el('preflight').textContent,/確認が必要/);assert.equal(storage.get('fieldrise-photo-v1'),before);
 document.createElement=tag=>{const e=original(tag);if(tag==='a')e.click=()=>{throw Error('private internal')};return e;};
 await el('downloadAll').onclick();assert.match(el('exportStatus').textContent,/ダウンロード開始失敗/);assert.ok(!el('exportStatus').textContent.includes('private'));assert.equal(el('downloadAll').disabled,false);assert.equal(storage.get('fieldrise-photo-v1'),before);
 document.createElement=original;URL.createObjectURL=create;el('temporaryCanvas').toBlob=cb=>cb({size:1,arrayBuffer:async()=>{throw Error('zip internal')}});await el('downloadAll').onclick();assert.match(el('exportStatus').textContent,/ZIP生成失敗/);assert.equal(storage.get('fieldrise-photo-v1'),before);el('temporaryCanvas').toBlob=cb=>cb(new Blob(['image']));
 });

test('artist search copy and manual Studio evidence persist through set reload',async()=>{el('newSet').onclick();assert.equal(el('studio_searchKeyword').value,'Runa-Girl8215');navigator.clipboard.writeText=async text=>el('clipboard').textContent=text;await el('copySearch').onclick();assert.equal(el('clipboard').textContent,'Runa-Girl8215');el('studio_state').value='候補あり';el('studio_observedTitle').value='cafe';el('studio_observedArtist').value='Runa-Girl8215';el('studio_observedDuration').value='00:59';el('studio_notes').value='分割曲候補を本人確認中';el('validateStudio').onclick();assert.match(el('studioResult').textContent,/候補あり/);el('setName').value='Studio evidence test';el('saveCurrent').onclick();const saved=JSON.parse(storage.get('fieldrise-photo-v1')).sets.at(-1);assert.equal(saved.studioSound.state,'候補あり');assert.equal(saved.ready,false);el('loadSet').onclick();assert.equal(el('studio_notes').value,'分割曲候補を本人確認中');el('studio_state').value='確認済み';el('validateStudio').onclick();assert.match(el('studioResult').textContent,/本人照合/);assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).sets.at(-1).studioSound.state,'候補あり');});
test('artist copy follows selected song and loaded immutable snapshot, handles failure without writes',async()=>{const before=storage.get('fieldrise-photo-v1');el('studio_searchKeyword').value='Custom keyword';navigator.clipboard.writeText=async text=>el('clipboard').textContent=text;await el('copySearch').onclick();assert.equal(el('clipboard').textContent,'Runa-Girl8215');assert.match(el('status').textContent,/アーティスト名をコピーしました/);assert.equal(storage.get('fieldrise-photo-v1'),before);el('songTitle').value='Synthetic';el('artist').value='Test Artist';el('duration').value='1:00';el('songForm').onsubmit({preventDefault(){}});await el('copySearch').onclick();assert.equal(el('clipboard').textContent,'Test Artist');el('setSelect').value=JSON.parse(storage.get('fieldrise-photo-v1')).sets.findIndex(s=>s.name==='Studio evidence test');el('loadSet').onclick();await el('copySearch').onclick();assert.equal(el('clipboard').textContent,'Runa-Girl8215');const stored=storage.get('fieldrise-photo-v1');navigator.clipboard.writeText=async()=>{throw Error('blocked')};await el('copySearch').onclick();assert.match(el('status').textContent,/手動コピー/);assert.equal(storage.get('fieldrise-photo-v1'),stored);});

test('owner publication consent and quota failure protect all sets; no automatic export',()=>{const before=storage.get('fieldrise-photo-v1');el('setState').value='投稿済み';el('publishedUrl').value='https://www.tiktok.com/@runa_girl8215/photo/123';el('publishedAt').value='2026-10-10T21:00';let clicks=0;const create=document.createElement;document.createElement=tag=>{const e=create(tag);if(tag==='a')e.click=()=>clicks++;return e;};globalThis.confirm=()=>false;el('changeSetState').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);globalThis.confirm=()=>true;const write=localStorage.setItem;localStorage.setItem=()=>{throw Error('quota')};el('changeSetState').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);assert.match(el('status').textContent,/既存データは変更していません/);localStorage.setItem=write;el('changeSetState').onclick();const after=JSON.parse(storage.get('fieldrise-photo-v1'));assert.equal(after.sets.length,JSON.parse(before).sets.length);assert.equal(after.sets.at(-1).status,'投稿済み');assert.equal(after.sets.at(-1).music.match,'未確認');assert.equal(clicks,0);assert.deepEqual(after.sets.slice(0,-1),JSON.parse(before).sets.slice(0,-1));document.createElement=create;});
test('incomplete draft retention remains a preparation warning and backup policy is visible',()=>{el('checkReady').onclick();assert.match(el('preflight').textContent,/下書き再編集時の音源保持未確認/);});

test('posted record requires explicit owner consent and quota failure is atomic',async()=>{globalThis.confirm=()=>true;el('newSet').onclick();await el('image').onchange({target:{files:[fixture('record-policy.png')]}});el('title').value='Policy';el('description').value='Owner draft';el('override').value='確認前の作業記録のみ';el('postUrl').value='https://www.tiktok.com/@runa_girl8215/photo/456';el('postedAt').value='2026-10-10T21:00:00+09:00';const before=storage.get('fieldrise-photo-v1');globalThis.confirm=()=>false;el('record').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);assert.match(el('status').textContent,/投稿完了未確認/);globalThis.confirm=()=>true;const write=localStorage.setItem;localStorage.setItem=()=>{throw Error('quota')};el('record').onclick();assert.equal(storage.get('fieldrise-photo-v1'),before);assert.match(el('status').textContent,/既存記録は変更していません/);localStorage.setItem=write;el('record').onclick();assert.equal(JSON.parse(storage.get('fieldrise-photo-v1')).records.length,JSON.parse(before).records.length+1);});
