import {test} from 'node:test';import assert from 'node:assert/strict';
import {music,record,migrate,merge,importPlan} from '../automation/sns_auto_posting/tiktok/photo/data.mjs';import {seed} from '../automation/sns_auto_posting/tiktok/photo/core.mjs';
const fresh=()=>migrate({songs:[music({...seed,id:'local-seed'})],records:[]});
const verified=()=>music({...seed,id:'backup-song',isrc:'JPABC2600001',soundOnId:'so1',tiktokId:'tt1',soundUrl:'https://www.tiktok.com/music/cafe-1',match:'確認済み',reviewer:'owner',verifiedAt:'2026-10-10T01:00:00Z',method:'manual',evidence:'test evidence',businessUse:'利用可（本人確認）',businessEvidence:'owner test evidence'});
const full=()=>{const music=verified();return {schemaVersion:6,songs:[music],records:[record({id:'r1',photoSetId:'s1',music,song:'cafe',description:'Manual English text',language:'en'})],sets:[{id:'s1',name:'English',createdAt:'2026-10-10T01:00:00Z',updatedAt:'2026-10-10T02:00:00Z',photos:[{id:'p1',name:'one.jpg',size:100,lastModified:1,ratio:'4:3',x:10,y:80}],music,title:'Edited',description:'Manual English text',hashtags:'#Cafe',language:'en',category:'カフェ・リラックス',status:'下書き',statusHistory:[{from:'',to:'下書き',at:'2026-10-10T01:00:00Z',reason:'original'}]}]};};
test('fresh seed full backup requires adoption consent, keeps incoming IDs references and snapshots',()=>{const a=fresh(),b=full(),before=JSON.stringify(a);const p=importPlan(a,b);assert.equal(p.seedReplacement,true);assert.match(p.summary,/初期楽曲/);assert.throws(()=>merge(a,b),/明示確認/);const r=merge(a,b,{allowSeedReplacement:true});assert.equal(r.songs.length,1);assert.equal(r.songs[0].id,'backup-song');assert.deepEqual(r.songs[0],verified());assert.equal(r.records[0].photoSetId,r.sets[0].id);assert.deepEqual(r.records[0].music,verified());assert.deepEqual(r.sets[0].music,verified());assert.equal(r.sets[0].language,'en');assert.equal(r.sets[0].photos[0].x,10);assert.equal(JSON.stringify(a),before);assert.deepEqual(migrate(JSON.parse(JSON.stringify(r))),r);});
test('v1 through v6 import into initial installation retain manual text and audit',()=>{for(let v=1;v<=6;v++){const b=full();b.schemaVersion=v;const r=merge(fresh(),b,{allowSeedReplacement:true});assert.equal(r.schemaVersion,6);assert.equal(r.records[0].description,'Manual English text');assert.equal(r.sets[0].statusHistory[0].reason,'original');assert.equal(r.songs[0].isrc,'JPABC2600001');}});
test('same ID fully equal song reused only after all fields compare, conflicting audit blocked',()=>{const a=migrate(full()),b={songs:[a.songs[0]],records:[record({id:'new',song:'cafe'})]};const p=importPlan(a,b);assert.equal(p.counts.reusedSongs,1);assert.equal(p.result.songs.length,1);for(const change of [{isrc:'JPABC2600002'},{soundOnId:'other'},{tiktokId:'other'},{evidence:'changed'},{match:'不一致'},{businessUse:'利用不可（本人確認）'}]){assert.throws(()=>importPlan(a,{...b,songs:[{...a.songs[0],...change}]}),/内容が異なります/);}});
test('different IDs potentially same music stop instead of dropping either version',()=>{const a=migrate(full());for(const song of [{...a.songs[0],id:'other'},{...a.songs[0],id:'other',title:'different'},{...a.songs[0],id:'other',duration:'1:00',seconds:60}])assert.throws(()=>importPlan(a,{songs:[song],records:[]}),/同一楽曲/);assert.throws(()=>importPlan(fresh(),{songs:[verified(),{...verified(),id:'other'}],records:[]}),/取込内/);});
test('edited or referenced seed cannot be adopted, unknown same ID conflict cannot overwrite',()=>{for(const a of [migrate({songs:[{...fresh().songs[0],search:'edited'}],records:[]}),migrate({songs:fresh().songs,records:[record({id:'old',music:fresh().songs[0]})]})])assert.throws(()=>importPlan(a,full()),/同一楽曲/);assert.throws(()=>importPlan(fresh(),{songs:[{...verified(),id:'local-seed',title:'different'}],records:[]}),/内容が異なります/);});
test('duplicate history/set IDs and missing live set reference reject atomically',()=>{const a=migrate(full()),before=JSON.stringify(a);for(const b of [full(),{songs:[{...verified(),id:'unrelated',title:'other',isrc:'',soundOnId:'',tiktokId:'',soundUrl:'',match:'未確認'}],records:[record({id:'new',photoSetId:'missing'})]}])assert.throws(()=>importPlan(a,b));assert.equal(JSON.stringify(a),before);});

test('planned workflow and sound refusals survive backup adoption without inference',()=>{const b=full();Object.assign(b.sets[0],{ready:true,distributionChecked:true,finalSoundChecked:true,status:'投稿予定',scheduledAt:'2026-10-12T03:00:00Z'});const r=merge(fresh(),b,{allowSeedReplacement:true});assert.equal(r.sets[0].status,'投稿予定');assert.equal(r.sets[0].scheduledAt,'2026-10-12T03:00:00.000Z');const denied=full();denied.songs[0].match='不一致';denied.songs[0].businessUse='利用不可（本人確認）';denied.sets[0].music={...denied.songs[0]};denied.records[0].music={...denied.songs[0]};denied.records[0].match='不一致';const imported=merge(fresh(),denied,{allowSeedReplacement:true});assert.equal(imported.songs[0].match,'不一致');assert.equal(imported.sets[0].ready,false);assert.equal(imported.songs[0].businessUse,'利用不可（本人確認）');});
